name: Pages

on:
  push:
    branches: [ fact ]
  pull_request:
    branches: [ fact ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: npm ci && npm run build:demo

    - name: Deploy Demos to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        build_dir: dist/demo
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
